#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Registrar o Carregador Automático
|--------------------------------------------------------------------------
|
| Composer fornece um carregador de classe gerado automaticamente e conveniente
| para nossa aplicação. Apenas precisamos utilizá-lo! O incluiremos
| neste script para que não precisemos nos preocupar com o
| carregamento manual de nenhuma de nossas classes. É ótimo relaxar.
|
*/

require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

// Cria o kernel do console e processa o comando recebido

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

// Termina o kernel para liberar recursos e encerrar a aplicação

$kernel->terminate($input, $status);

exit($status);
